services:
  database:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_DB},pinkka_test_db
    ports:
      - "5432:5432"
    volumes:
      - pinkka_db:/var/lib/postgresql
      - ./scripts/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh

volumes:
  pinkka_db:
